server:
  port: 8089

spring:
  application:
    name: operis-project-service
  datasource:
    url: jdbc:mysql://localhost:4444/operis-project?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

code:
    secret: mAvsZD2KqE2Kv6VpF+VkN1P3PT+2uq5z0g2ZxF0StSc=

logging:
    level:
        root: INFO
        com.operis: INFO
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/